spring:
  application:
    name: taskTime

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      auto-commit: true
      connection-timeout: 20000
      minimum-idle: 2
      maximum-pool-size: 3
      pool-name: TaskTimeHikariCP
      max-lifetime: 1200000
      connection-test-query: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: taskTime

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
    schemas: taskTime
    clean-disabled: true
    validate-on-migrate: true

use:
  real:
    database: true