name: Build and push 
run-name: ${{github.actor}} Building and pushing TaskTime
on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
      - 'feature/*'
      - 'bugfix/*'

jobs: 
  build: 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      - name: Setup GraalVm
        uses: graalvm/setup-graalvm@v1
        with: 
          distribution: 'graalvm'
          java-version: 25
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Build project
        run: ./gradlew build nativeCompile
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/clarenced/tasktime:${{ github.sha }}
